version: "3.8"

services:
  excalidraw:
    stdin_open: true
    build:
      context: .
      target: development
    container_name: excalidraw
    ports:
      - "3000:3000"
    restart: on-failure
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - node_modules:/opt/node_app/node_modules
      - ./:/opt/node_app/

  excalidraw-storage-backend:
    build:
      context: https://github.com/SWEETGOOD-DE/excalidraw-storage-backend.git#main
      target: production
    depends_on:
      # Change this accordingly if you want to use another storage backend than redis
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Change this accordingly if you want to use another storage backend than redis
      STORAGE_URI: redis://:${REDIS_PASSWORD}@redis:6379
      STORAGE_TTL: 2592000000

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: always
    ports:
      - "5001:80"

  # Change this accordingly if you want to use another storage backend than redis
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: "[ $$(redis-cli -a ${REDIS_PASSWORD} ping) = 'PONG' ]"
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  node_modules:
